### ISSUE TITLE
About dfkz_data

### ISSUE THREAD

**Issue by yjhong89** [VLL-HD/FrEIA#17] opened 2019-12-13 12:54 UTC
Hi.

I am trying to do some experiments in your paper especially inverse problems in natural science.

In FrEIA/experiments/inverse_problems_science folder, there is a symbolic link to '../datasets/dkfz' 
but I cannot find any *.npy data files in this repository.

Can you let me know how I can deal with this? Or is those data confidential to be released in public?

Thanks in advance.

Best regards,
YJ Hong.

**Comment by redraven984** [comment] 2020-01-31 17:23
I'm having the same issue. Did you solve it?

**Comment by yjhong89** [comment] 2020-02-04 13:15
@redraven984 
Nope, I found this comment at README
![image](https://user-images.githubusercontent.com/26890721/73747929-ccd16780-479b-11ea-9567-12a7cc5fe2d5.png)

**Comment by redraven984** [comment] 2020-02-05 20:44
Not particularly helpful since formatting the datasets for the experiment is an essential part of the solution.

Were you able to run the framework on your data?

**Comment by yjhong89** [comment] 2020-02-06 12:20
Not actually. 

I just did the gaussian mixture toy example.

**Comment by ardizzone** [comment] 2021-02-09 12:14
Hi!
Sorry for the late response.
We are aware, our collaborators for the astorphysics and medical applications did not release their data.
I will try asking around.

I will close this issue, because it is a duplicate of
https://github.com/VLL-HD/analyzing_inverse_problems/issues/2

**Closed by ardizzone** 2021-02-09 12:14 UTC
